/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserSettings = IDL.Record({
  'notifications' : IDL.Bool,
  'showOnlineStatus' : IDL.Bool,
  'showInRadius' : IDL.Bool,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'updatedAt' : Time,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'vipStatus' : IDL.Text,
  'username' : IDL.Text,
  'radiusTier' : IDL.Nat,
  'displayName' : IDL.Text,
  'settings' : UserSettings,
  'lastSeen' : Time,
  'location' : IDL.Opt(Location),
  'avatar' : IDL.Text,
  'online' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'vipStatus' : IDL.Text,
  'username' : IDL.Text,
  'radiusTier' : IDL.Nat,
  'displayName' : IDL.Text,
  'settings' : UserSettings,
  'lastSeen' : Time,
  'location' : IDL.Opt(Location),
  'avatar' : IDL.Text,
  'online' : IDL.Bool,
});
export const Message = IDL.Record({
  'seen' : IDL.Bool,
  'text' : IDL.Text,
  'recipient' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Text,
  'longitude' : IDL.Text,
});
export const PurchaseSettings = IDL.Record({
  'basicPrice' : IDL.Nat,
  'premiumPrice' : IDL.Nat,
  'enabled' : IDL.Bool,
  'standardPrice' : IDL.Nat,
});
export const UserInput = IDL.Record({
  'id' : IDL.Text,
  'vipStatus' : IDL.Text,
  'username' : IDL.Text,
  'radiusTier' : IDL.Nat,
  'displayName' : IDL.Text,
  'passwordHash' : IDL.Text,
  'avatar' : IDL.Text,
});
export const LocationInput = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});

export const idlService = IDL.Service({
  'broadcastMessage' : IDL.Func([IDL.Text], [], []),
  'deleteConversation' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteMessage' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
  'deleteOwnAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'follow' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getCoordinates' : IDL.Func([], [IDL.Opt(Coordinates)], ['query']),
  'getFollowers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getFollowing' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getLatestBroadcast' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'text' : IDL.Text, 'timestamp' : Time }))],
      ['query'],
    ),
  'getNewMessages' : IDL.Func(
      [IDL.Text, IDL.Text, Time],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getPurchaseSettings' : IDL.Func([], [PurchaseSettings], ['query']),
  'getTotalUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUnreadCount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
  'getUserById' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'markConversationSeen' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'register' : IDL.Func([UserInput], [User], []),
  'removeFollower' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCoordinates' : IDL.Func([Coordinates], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setOnlineStatus' : IDL.Func([IDL.Text, IDL.Bool], [User], []),
  'setPurchaseSettings' : IDL.Func([PurchaseSettings], [], []),
  'setUserVipStatus' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'unfollow' : IDL.Func([IDL.Text], [IDL.Text], []),
  'updateAvatar' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'updateLocation' : IDL.Func([IDL.Text, LocationInput], [User], []),
  'updateSettings' : IDL.Func([IDL.Text, UserSettings], [User], []),
  'updateUserRadiusTier' : IDL.Func([IDL.Text, IDL.Nat], [User], []),
  'verifyCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(User)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserSettings = IDL.Record({
    'notifications' : IDL.Bool,
    'showOnlineStatus' : IDL.Bool,
    'showInRadius' : IDL.Bool,
  });
  const Location = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'updatedAt' : Time,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'vipStatus' : IDL.Text,
    'username' : IDL.Text,
    'radiusTier' : IDL.Nat,
    'displayName' : IDL.Text,
    'settings' : UserSettings,
    'lastSeen' : Time,
    'location' : IDL.Opt(Location),
    'avatar' : IDL.Text,
    'online' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'vipStatus' : IDL.Text,
    'username' : IDL.Text,
    'radiusTier' : IDL.Nat,
    'displayName' : IDL.Text,
    'settings' : UserSettings,
    'lastSeen' : Time,
    'location' : IDL.Opt(Location),
    'avatar' : IDL.Text,
    'online' : IDL.Bool,
  });
  const Message = IDL.Record({
    'seen' : IDL.Bool,
    'text' : IDL.Text,
    'recipient' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Text,
    'longitude' : IDL.Text,
  });
  const PurchaseSettings = IDL.Record({
    'basicPrice' : IDL.Nat,
    'premiumPrice' : IDL.Nat,
    'enabled' : IDL.Bool,
    'standardPrice' : IDL.Nat,
  });
  const UserInput = IDL.Record({
    'id' : IDL.Text,
    'vipStatus' : IDL.Text,
    'username' : IDL.Text,
    'radiusTier' : IDL.Nat,
    'displayName' : IDL.Text,
    'passwordHash' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const LocationInput = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
  });
  
  return IDL.Service({
    'broadcastMessage' : IDL.Func([IDL.Text], [], []),
    'deleteConversation' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteMessage' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
    'deleteOwnAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'follow' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getCoordinates' : IDL.Func([], [IDL.Opt(Coordinates)], ['query']),
    'getFollowers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getFollowing' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getLatestBroadcast' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'text' : IDL.Text, 'timestamp' : Time }))],
        ['query'],
      ),
    'getNewMessages' : IDL.Func(
        [IDL.Text, IDL.Text, Time],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getPurchaseSettings' : IDL.Func([], [PurchaseSettings], ['query']),
    'getTotalUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUnreadCount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
    'getUserById' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'markConversationSeen' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'register' : IDL.Func([UserInput], [User], []),
    'removeFollower' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCoordinates' : IDL.Func([Coordinates], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setOnlineStatus' : IDL.Func([IDL.Text, IDL.Bool], [User], []),
    'setPurchaseSettings' : IDL.Func([PurchaseSettings], [], []),
    'setUserVipStatus' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'unfollow' : IDL.Func([IDL.Text], [IDL.Text], []),
    'updateAvatar' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'updateLocation' : IDL.Func([IDL.Text, LocationInput], [User], []),
    'updateSettings' : IDL.Func([IDL.Text, UserSettings], [User], []),
    'updateUserRadiusTier' : IDL.Func([IDL.Text, IDL.Nat], [User], []),
    'verifyCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(User)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };