/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coordinates { 'latitude' : string, 'longitude' : string }
export interface Location { 'lat' : number, 'lng' : number, 'updatedAt' : Time }
export interface LocationInput { 'lat' : number, 'lng' : number }
export interface Message {
  'seen' : boolean,
  'text' : string,
  'recipient' : string,
  'sender' : string,
  'timestamp' : Time,
}
export interface PurchaseSettings {
  'basicPrice' : bigint,
  'premiumPrice' : bigint,
  'enabled' : boolean,
  'standardPrice' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface User {
  'id' : string,
  'vipStatus' : string,
  'username' : string,
  'radiusTier' : bigint,
  'displayName' : string,
  'settings' : UserSettings,
  'lastSeen' : Time,
  'location' : [] | [Location],
  'avatar' : string,
  'online' : boolean,
}
export interface UserInput {
  'id' : string,
  'vipStatus' : string,
  'username' : string,
  'radiusTier' : bigint,
  'displayName' : string,
  'passwordHash' : string,
  'avatar' : string,
}
export interface UserProfile {
  'id' : string,
  'vipStatus' : string,
  'username' : string,
  'radiusTier' : bigint,
  'displayName' : string,
  'settings' : UserSettings,
  'lastSeen' : Time,
  'location' : [] | [Location],
  'avatar' : string,
  'online' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'notifications' : boolean,
  'showOnlineStatus' : boolean,
  'showInRadius' : boolean,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'broadcastMessage' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteConversation' : ActorMethod<[string, string], undefined>,
  'deleteMessage' : ActorMethod<[string, string, Time], undefined>,
  'deleteUser' : ActorMethod<[string], undefined>,
  'deleteOwnAccount' : ActorMethod<[string, string], boolean>,
  'follow' : ActorMethod<[string], string>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[string, string], Array<Message>>,
  'getCoordinates' : ActorMethod<[], [] | [Coordinates]>,
  'getFollowers' : ActorMethod<[string], Array<string>>,
  'getFollowing' : ActorMethod<[string], Array<string>>,
  'getLatestBroadcast' : ActorMethod<
    [],
    [] | [{ 'text' : string, 'timestamp' : Time }]
  >,
  'getNewMessages' : ActorMethod<[string, string, Time], Array<Message>>,
  'getPurchaseSettings' : ActorMethod<[], PurchaseSettings>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalUnreadCount' : ActorMethod<[string], bigint>,
  'getUnreadCount' : ActorMethod<[string, string], bigint>,
  'getUserById' : ActorMethod<[string], [] | [User]>,
  'getUserByUsername' : ActorMethod<[string], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markConversationSeen' : ActorMethod<[string, string], undefined>,
  'register' : ActorMethod<[UserInput], User>,
  'removeFollower' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCoordinates' : ActorMethod<[Coordinates], undefined>,
  'sendMessage' : ActorMethod<[string, string, string], undefined>,
  'setOnlineStatus' : ActorMethod<[string, boolean], User>,
  'setPurchaseSettings' : ActorMethod<[PurchaseSettings], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUserVipStatus' : ActorMethod<[string, string], User>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unfollow' : ActorMethod<[string], string>,
  'updateAvatar' : ActorMethod<[string, string], User>,
  'updateLocation' : ActorMethod<[string, LocationInput], User>,
  'updateSettings' : ActorMethod<[string, UserSettings], User>,
  'updateUserRadiusTier' : ActorMethod<[string, bigint], User>,
  'verifyCredentials' : ActorMethod<[string, string], [] | [User]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];