/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const UserSettings = IDL.Record({
  'notifications' : IDL.Bool,
  'showOnlineStatus' : IDL.Bool,
  'showInRadius' : IDL.Bool,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'updatedAt' : Time,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'vipStatus' : IDL.Text,
  'username' : IDL.Text,
  'radiusTier' : IDL.Nat,
  'displayName' : IDL.Text,
  'settings' : UserSettings,
  'lastSeen' : Time,
  'location' : IDL.Opt(Location),
  'avatar' : IDL.Text,
  'online' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'vipStatus' : IDL.Text,
  'username' : IDL.Text,
  'radiusTier' : IDL.Nat,
  'displayName' : IDL.Text,
  'settings' : UserSettings,
  'lastSeen' : Time,
  'location' : IDL.Opt(Location),
  'avatar' : IDL.Text,
  'online' : IDL.Bool,
});
export const Message = IDL.Record({
  'seen' : IDL.Bool,
  'text' : IDL.Text,
  'recipient' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Text,
  'longitude' : IDL.Text,
});
export const PurchaseSettings = IDL.Record({
  'basicPrice' : IDL.Nat,
  'premiumPrice' : IDL.Nat,
  'enabled' : IDL.Bool,
  'standardPrice' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const UserInput = IDL.Record({
  'id' : IDL.Text,
  'vipStatus' : IDL.Text,
  'username' : IDL.Text,
  'radiusTier' : IDL.Nat,
  'displayName' : IDL.Text,
  'passwordHash' : IDL.Text,
  'avatar' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const LocationInput = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'broadcastMessage' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteConversation' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteMessage' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'deleteOwnAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteOwnAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'follow' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getCoordinates' : IDL.Func([], [IDL.Opt(Coordinates)], ['query']),
  'getFollowers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getFollowing' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getLatestBroadcast' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'text' : IDL.Text, 'timestamp' : Time }))],
      ['query'],
    ),
  'getNewMessages' : IDL.Func(
      [IDL.Text, IDL.Text, Time],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getPurchaseSettings' : IDL.Func([], [PurchaseSettings], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUnreadCount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
  'getUserById' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markConversationSeen' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'register' : IDL.Func([UserInput], [User], []),
  'removeFollower' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCoordinates' : IDL.Func([Coordinates], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setOnlineStatus' : IDL.Func([IDL.Text, IDL.Bool], [User], []),
  'setPurchaseSettings' : IDL.Func([PurchaseSettings], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUserVipStatus' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unfollow' : IDL.Func([IDL.Text], [IDL.Text], []),
  'updateAvatar' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'updateLocation' : IDL.Func([IDL.Text, LocationInput], [User], []),
  'updateSettings' : IDL.Func([IDL.Text, UserSettings], [User], []),
  'updateUserRadiusTier' : IDL.Func([IDL.Text, IDL.Nat], [User], []),
  'verifyCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(User)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const UserSettings = IDL.Record({
    'notifications' : IDL.Bool,
    'showOnlineStatus' : IDL.Bool,
    'showInRadius' : IDL.Bool,
  });
  const Location = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'updatedAt' : Time,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'vipStatus' : IDL.Text,
    'username' : IDL.Text,
    'radiusTier' : IDL.Nat,
    'displayName' : IDL.Text,
    'settings' : UserSettings,
    'lastSeen' : Time,
    'location' : IDL.Opt(Location),
    'avatar' : IDL.Text,
    'online' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'vipStatus' : IDL.Text,
    'username' : IDL.Text,
    'radiusTier' : IDL.Nat,
    'displayName' : IDL.Text,
    'settings' : UserSettings,
    'lastSeen' : Time,
    'location' : IDL.Opt(Location),
    'avatar' : IDL.Text,
    'online' : IDL.Bool,
  });
  const Message = IDL.Record({
    'seen' : IDL.Bool,
    'text' : IDL.Text,
    'recipient' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Text,
    'longitude' : IDL.Text,
  });
  const PurchaseSettings = IDL.Record({
    'basicPrice' : IDL.Nat,
    'premiumPrice' : IDL.Nat,
    'enabled' : IDL.Bool,
    'standardPrice' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const UserInput = IDL.Record({
    'id' : IDL.Text,
    'vipStatus' : IDL.Text,
    'username' : IDL.Text,
    'radiusTier' : IDL.Nat,
    'displayName' : IDL.Text,
    'passwordHash' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const LocationInput = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'broadcastMessage' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteConversation' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteMessage' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'follow' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getCoordinates' : IDL.Func([], [IDL.Opt(Coordinates)], ['query']),
    'getFollowers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getFollowing' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getLatestBroadcast' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'text' : IDL.Text, 'timestamp' : Time }))],
        ['query'],
      ),
    'getNewMessages' : IDL.Func(
        [IDL.Text, IDL.Text, Time],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getPurchaseSettings' : IDL.Func([], [PurchaseSettings], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUnreadCount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
    'getUserById' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markConversationSeen' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'register' : IDL.Func([UserInput], [User], []),
    'removeFollower' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCoordinates' : IDL.Func([Coordinates], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setOnlineStatus' : IDL.Func([IDL.Text, IDL.Bool], [User], []),
    'setPurchaseSettings' : IDL.Func([PurchaseSettings], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUserVipStatus' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unfollow' : IDL.Func([IDL.Text], [IDL.Text], []),
    'updateAvatar' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'updateLocation' : IDL.Func([IDL.Text, LocationInput], [User], []),
    'updateSettings' : IDL.Func([IDL.Text, UserSettings], [User], []),
    'updateUserRadiusTier' : IDL.Func([IDL.Text, IDL.Nat], [User], []),
    'verifyCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(User)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };